; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

; --------------------------------------------------------------------------------------------
; --- Settings for STM32U585CIU6 (WeAct Mini Core) ---
; --- Method1 ---
; --------------------------------------------------------------------------------------------
[env:stm32u585-method1]
platform = ststm32
framework = arduino
board = genericSTM32U585CIU6_custom

monitor_speed = 115200
monitor_dtr = 1

build_src_filter =
  +<*>
  ;-<method2.cpp>
  +<method1.cpp>

lib_deps =

build_flags =
  -O3
  -ffast-math
  -funroll-loops

  -D PIO_FRAMEWORK_ARDUINO_ENABLE_CDC
  -D USBCON
  -D STM32U585xx

upload_protocol = dfu

; --------------------------------------------------------------------------------------------
; --- Settings for STM32U585CIU6 DEBUG ---
; --- Method1 ---
; --------------------------------------------------------------------------------------------
[env:stm32u585-method1-debug]
platform = ststm32
framework = arduino
board = genericSTM32U585CIU6_custom

monitor_speed = 115200
monitor_dtr = 1

build_src_filter =
  +<*>
  ;-<method2.cpp>
  +<method1.cpp>

lib_deps =

build_type = debug

build_flags =
  -Og
  -g3

  -D PIO_FRAMEWORK_ARDUINO_ENABLE_CDC
  -D USBCON
  -D STM32U585xx

upload_protocol = stlink
debug_tool = stlink
debug_init_break = tbreak setup

debug_build_flags =
  -Og
  -g3

debug_extra_cmds =
  monitor reset halt